export const NOTIFICATIONS_READ = 'NOTIFICATIONS_READ';
export const NOTIFICATIONS_UNREAD = 'NOTIFICATIONS_UNREAD';
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_NOTIFICATIONS_COUNT = 'GET_NOTIFICATIONS_COUNT';