export const SET_NOTIFICATIONS_READ = 'SET_NOTIFICATIONS_READ';
export const SET_NOTIFICATIONS_UNREAD = 'SET_NOTIFICATIONS_UNREAD';
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_NOTIFICATIONS_COUNT = 'GET_NOTIFICATIONS_COUNT';